### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by hsm207** [kyunghyuncho/bert-gen#1]
Hello,

Your work looks interesting.

Could you provide some instructions as to how to start generating sample sentences?

**Comment by kyunghyuncho** [comment]
@W4ngatang

**Comment by QiaoranC** [comment]
I am curious too, i tried demo, but not fully understand.

**Comment by iuria21** [comment]
also interested!

**Comment by W4ngatang** [comment]
Check out this notebook! 

https://colab.research.google.com/drive/1MxKZGtQ9SSBjTK5ArsZ5LKhkztzg52RV#scrollTo=0VzY3scBYc3H

The non ipynb files are actually actively not supported.

**Comment by iuria21** [comment]
Hi! thanks for the answer. I was thinking if this could be used to paraphrase sentences, in order to achieve similar new sentences. 
Thanks!

**Comment by W4ngatang** [comment]
Seems worth a shot! You'd have to make it conditional somehow.
