### ISSUE TITLE
How about Perplexity? (in addition to BLEU)

### ISSUE THREAD

**Issue by leejason** [kyunghyuncho/bert-gen#2]
The colab example using BLEU is helpful & thanks. I'm wondering whether there is any plan to measure by PPL (Perplexity). Or any pointer showing how to measure the performance of generative models by PPL in general?

**Comment by W4ngatang** [comment]
In general it's very difficult to estimate the perplexity of a given sentence according to BERT. The best you could do is likely just compute an upper bound.
